spring:
  datasource:
    dynamic:
      primary: master
      datasource:
        master:
          username: root
          password: admin
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://127.0.0.1:3306/world
        slave:
          username: root
          password: admin
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://127.0.0.1:3306/vhr